In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [33]:
df=pd.read_csv("mtcars.csv")

In [34]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64  
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64  
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64  
 8   am      32 non-null     int64  
 9   gear    32 non-null     int64  
 10  carb    32 non-null     int64  
dtypes: float64(5), int64(6)
memory usage: 2.9 KB


In [36]:
x=df.drop("mpg",axis=1)
y=df["mpg"]

In [37]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [40]:
model=LinearRegression()

In [41]:
model_lr=model.fit(x_train,y_train)

In [42]:
y_train_pred=model_lr.predict(x_train)
y_test_pred=model_lr.predict(x_test)

In [43]:
print(" Train r2 score:",r2_score(y_train,y_train_pred))
print("Test r2 score:",r2_score(y_test,y_test_pred))

 Train r2 score: 0.87103867934196
Test r2 score: 0.8040132391853168


In [44]:
model_lr.coef_

array([-1.1064411 ,  2.71521665, -1.22769455,  0.44423469, -4.75022064,
        2.82003922, -0.76799368,  0.69422073,  0.76614335,  0.57540635])

# Ridge

In [54]:
from sklearn.linear_model import Ridge

In [55]:
ridge=Ridge(alpha=20)

In [56]:
model_ridge=ridge.fit(x_train,y_train)

In [57]:
y_train_pred=model_ridge.predict(x_train)
y_test_pred=model_ridge.predict(x_test)

In [58]:
print("Train r2 score:",r2_score(y_train,y_train_pred))
print("Test r2 score:",r2_score(y_test,y_test_pred))

Train r2 score: 0.8246952882738724
Test r2 score: 0.8254825210900597


In [59]:
model_ridge.coef_

array([-0.71424048, -0.67423575, -0.7420988 ,  0.57789706, -0.98543679,
        0.29949323,  0.42218245,  0.60318631,  0.47751416, -0.54775332])

# Lasso

In [60]:
from sklearn.linear_model import Lasso

In [61]:
model=Lasso(alpha=0.5)

In [62]:
model_lasso=model.fit(x_train,y_train)

In [63]:
y_train_pred=model_lasso.predict(x_train)
y_test_pred=model_lasso.predict(x_test)

In [64]:
print("Train r2 score:",r2_score(y_train,y_train_pred))
print("Test r2 score:",r2_score(y_test,y_test_pred))

Train r2 score: 0.8396229770821304
Test r2 score: 0.8284869466359543


In [65]:
model_lasso.coef_

array([-1.54350437, -0.        , -1.00325924,  0.15549042, -2.49372285,
        0.        ,  0.        ,  0.26218624,  0.        , -0.        ])

# Elastic Net

In [66]:
from sklearn.linear_model import ElasticNet

In [68]:
elasticnet=ElasticNet(alpha=0.5,l1_ratio=0.5)

In [69]:
model_elasticnet=elasticnet.fit(x_train,y_train)

In [70]:
y_train_pred=model_elasticnet.predict(x_train)
y_test_pred=model_elasticnet.predict(x_test)

In [71]:
print("Train r2 score:",r2_score(y_train,y_train_pred))
print("Test r2 score:",r2_score(y_test,y_test_pred))

Train r2 score: 0.8385003834317929
Test r2 score: 0.8393535012393709


In [72]:
model_elasticnet.coef_

array([-0.87890082, -0.5757604 , -0.98621545,  0.49991582, -1.42458397,
        0.08663879,  0.26788906,  0.561996  ,  0.29680483, -0.46851265])